### PR TITLE
Add Oceanic Next Theme

### PR DESCRIPTION
**Pull request by voronianski**
https://github.com/voronianski/oceanic-next-theme

### CODE REVIEW

**Comment by zertosh** [comment]
@voronianski Oh I reallyyyy like it. Let me test drive it for a day or two :smile:

**Comment by voronianski** [comment]
@zertosh thanks! Let me know if you'll have some suggests :smiley:

**Comment by gpbl** [comment]
@voronianski what is the font in the screenshots?

**Comment by voronianski** [comment]
@gpbl Inconsolata http://levien.com/type/myfonts/inconsolata.html

**Comment by gpbl** [comment]
ah the famous one! thanks i'll try it :+1:

**Comment by Dashed** [comment]
Damn. This looks sexy. Easy on the eyes too.

I'll be test driving this for a bit as well.

**Comment by sebmck** [comment]
I actually really like this. I've been using Base 16 Dark with my own custom syntax highlighting bundle but I'm trying out this and 6to5-sublime.

**Comment by zertosh** [comment]
Out of curiosity, what are you guys using for UI themes? https://github.com/kkga/spacegray? https://github.com/buymeasoda/soda-theme?

**Comment by voronianski** [comment]
@zertosh I'm using - https://github.com/iccir/El-Capitan-Theme

**Comment by Dashed** [comment]
I'm still riding on default UI :smile:

**Comment by zertosh** [comment]
This is a very dangerous path to go down - I've wasted entire days tweaking settings heh - but I run [Soda Dark](https://github.com/buymeasoda/soda-theme) with the sidebar icons removed.

Pro-tip: You don't have to fork themes to make changes, just have an equivalently named theme in your `user` folder and it'll get merged with the packaged one. So I have a `User/Soda Dark 3.sublime-theme` with:

```json
[
  {
      "class": "icon_file_type",
      "content_margin": [0,0],
      "layer0.opacity": 0.0
  },
  {
      "class": "icon_folder",
      "layer0.texture": "",
      "layer0.opacity": 0.0,
      "content_margin": [0,0]
  },
  {
      "class": "icon_folder_loading",
      "content_margin": [0,0],
      "layer0.opacity": 0.0
  }
]
```

**Comment by zertosh** [comment]
Hey @voronianski, after thinking about it, I think it's best to keep the themes as a separate biz. It's pretty  frictionless to install a new theme package, and I don't want to start the precedent that we maintain themes. I'm keeping `Next` because it's not a theme people actually use, it's more of a debug theme that colors (nearly) every scope individually. And Monokai, well, it's kinda stuck now.

However, I would very much like to have a "featured" or "suggested" themes section right above the `About`. Want to make a PR to start the section with oceanic-next-theme? I'm moving the snippets chart into it's own doc, so that should put it up a little higher. I do ask that the screenshot be 728px wide so GitHub doesn't scale it.

Congrats on the theme btw! You have 2 more stars right now than this repo :star:

**Comment by voronianski** [comment]
@zertosh thanks, I'll do a PR :smiley:

**Comment by voronianski** [comment]
@zertosh https://github.com/babel/babel-sublime/pull/40

**Pull request closed without merging**
