### PR TITLE
Add support for styled-components

### PR DESCRIPTION
**Pull request by garetmckinley**
This PR adds support for [styled-components](https://github.com/styled-components/styled-components). They're a pretty big deal right now and have a good chance of becoming a standard. I think it would be awesome if you considered merging this upstream 😄 

You can view a preview of the implementation here: http://garetmckinley.github.io/styled-babel-sublime

### CODE REVIEW

**Comment by mxstbr** [comment]
Syntax highlighting is a part of a great experience when using`styled-components`. It's non-intrusive, meaning users who do not use `styled-components` won't notice any difference – but those who do definitely will.

In fact, the same syntax highlighting support [was also added to Atom's `language-babel` package](https://github.com/gandm/language-babel/commit/a2b9cd75a5c3f2d62224f03c0db0c7081c36e547) and people have only loved it so far!

We're working really hard to make `styled-components` the default solution for react apps. We think we nailed the development experience, and now we're working on further tools to get a slimmer filesize and even better performance.

----

> have a good chance of becoming a standard

See [this tweet](https://twitter.com/dan_abramov/status/786586964531097604) 👍

**Comment by zertosh** [comment]
Cool. We can do this. A few things: (1) What's with all of the unrelated changes? (2) Docs? (3) Tests?

**Comment by garetmckinley** [comment]
What unrelated changes are you referring to? The branch attached to this PR should only have changes related to integrating `styled-components`. I have been patching things in this branch for a week though, so it got a little cluttered up. If you'd prefer I can start back from upstream and patch in only the final changes as a single commit.

For docs, want me to add a new section to the `README` to talk about `styled-components` integration with a few examples?

For testing, do I just need to create a new `test/syntax_test_styles` with all the possible matches? Or is there a way these files are getting generated?


Thanks

**Comment by zertosh** [comment]
> What unrelated changes are you referring to?

* The `firstLineMatch` removal.
* Re-sorting the rules.
* Removing the comments.

> If you'd prefer I can start back from upstream and patch in only the final changes as a single commit.

Yes please :)

> For docs, want me to add a new section to the README to talk about styled-components integration with a few examples?

That would be great!

> For testing, do I just need to create a new test/syntax_test_styles with all the possible matches? Or is there a way these files are getting generated?

I don't know if you can auto-generate them. Just something that tests that the `source.react.css` scope is applied where you expect.

**Comment by garetmckinley** [comment]
Ok, thanks! I appreciate your input and the consideration of this PR 👍 I'll get to these changes this afternoon.

**Comment by garetmckinley** [comment]
I do have one question about this repo, what is the point of the `JavaScript (Babel).tmLanguage` file? In the README, it specifies that only ST3 is supported, which means that with the `sublime-syntax` file present, the `tmLanguage` file is ignored. Correct me if I'm wrong on this.

**Comment by zertosh** [comment]
> Correct me if I'm wrong on this.

You're right, but only if you're using the latest ST3 beta build - not all ST3's supported `sublime-syntax`. Very shortly (2 weeks maybe? I have an 8 hrs flight coming up to do this), I'm removing the `sublime-syntax` and only keeping the `tmLanguage`. The idea is to have one grammar that works in ST3, Atom and VSCode. The current `tmLanguage` sucks. However, [TypeScript's](https://github.com/Microsoft/TypeScript-TmLanguage) just got a re-write, and it's perfect to adapt to Flow-typed JS. This why I'm asking you for a test - I don't use `styled-components`, so I want to be able to catch breakage when I make the switch.

**Comment by mxstbr** [comment]
> This why I'm asking you for a test - I don't use styled-components, so I want to be able to catch breakage when I make the switch.

That sounds very reasonable 👌

**Comment by garetmckinley** [comment]
Ah, that makes sense. I'm working on the test file now, almost done. I already had implemented the support for `styled-components` in both the `tmLanguage` and `sublime-syntax` files, do you want me to include the changes in both those files until you actually remove the `sublime-syntax` from the repo?

It's no extra work for me either way since I had already written the code, just wanna make sure I include only the changes you want.

**Comment by zertosh** [comment]
Yes please, include both. I suspect that most (if not all) users will use the `sublime-syntax` implementation, but it would be nice if I had something already in the `tmLanguage` that I can copy/paste 😄

**Comment by bhough** [comment]
@garetmckinley @zertosh anything I can do here to help move this along?

**Comment by garetmckinley** [comment]
Hmm, I see that the repo has been updated recently! Basically we just need to make a fresh fork of the master repo and then patch in some of my changes. The main changes are in the new [Styled Components.tmLanguage](https://github.com/garetmckinley/styled-babel-sublime/blob/8b61498bd72c7408a9127624802758611d2cd573/Styled%20Components.tmLanguage) file.

I don't have time today, but I can definitely get to this and have it wrapped up tomorrow.

**Comment by zertosh** [comment]
@garetmckinley can you rebase it onto master and only do the `tmLanguage`?

**Comment by mxstbr** [comment]
Amazing, can't wait to land this! 🎉

**Comment by garetmckinley** [comment]
So I cleaned up this branch's history and got it ready for merging 😸  

I added better language definitions to the `Styled Components.tmLanguage` file. It even supports using css-only sublime extensions inside the embedded CSS! Like the css color preview extension shown in the screenshot 😄 

I also added fairly extensive tests for the `Styled Components.tmLanguage` file.

preview

Let me know if there's anything else you need me to do before we get this merged!

**Comment by mxstbr** [comment]
That's amazing, looks really really good @garetmckinley!

**Comment by zertosh** [comment]
@garetmckinley did you edit `JavaScript (Babel).tmLanguage` directly? Check out https://github.com/babel/babel-sublime#contributing.

**Comment by garetmckinley** [comment]
Yup. That section confused me, as theres no `YAML-tmKittens` file. I thought maybe it was referring to the YAML-tmLanguage file, but looking at the repo that file hasnt been updated in nearly a year. Let me know what you want me to edit and ill get it changed.

At this point im just moving around regex haha so its no big deal.

**Comment by zertosh** [comment]
yes, please update the `YAML-tmLanguage` file since that's what is used to generate the `tmLanguage` file.

**Comment by garetmckinley** [comment]
You got  it :+1:

**Comment by garetmckinley** [comment]
This PR should be ready to go @zertosh. The `styled-components` blocks were ported to the YAML file and I rebuilt the `tmLanguage` file using the updated template as well. I also got all 112 syntax tests passing as well 👍

**Comment by zertosh** [comment]
Thanks @garetmckinley! I need to get a few more changes in before I put out a release, so it'll be a few more days.

**Comment by garetmckinley** [comment]
No worries, I'm glad we were able to get this merged! I apologize for my misunderstanding how to use the DevTools, this was my first time working on a syntax package. I feel like I learned a lot though and I really appreciate your patience and willingness to help ☺️

**Comment by declanelcocks** [comment]
@zertosh As someone who's been looking forward to seeing syntax highlighting for `styled-components`, would appreciate a comment here to let us know when it's released! 😄 Or is there somewhere I can monitor to keep up-to-date with the releases for `babel-sublime`?

**Comment by protoEvangelium** [comment]
@zertosh @garetmckinley This is awesome guys!  Thanks for putting in the work to make this happen.  Will this update in the sublime babel package automatically?  Or is there something we need to do to apply this new syntax highlighting?

**Comment by jeanmichelcote** [comment]
Been looking forward to this as well. Thanks for building it!

**Comment by garetmckinley** [comment]
@protoEvangelium I'm still awaiting word from @zertosh on when the new version is out, so best we can do now is sit tight and wait for it to be released. Once it's out, you'll have `styled-components` support when you update your Sublime packages :)

**Comment by zertosh** [comment]
Sorry - the way that this captures whitespace is causing theme issues.... but I'll ship it like that

**Comment by garetmckinley** [comment]
No need to ship something that has issues. Do you have screenshots or anything to demonstrate what you are referring to? I didn't notice any issues like that when testing it

**Comment by zertosh** [comment]
Since you match whitespace like this:

```
\s*+(?:(?:injectGlobal))\s*((`))
^^^ whitespace

\s*+(?:(?:keyframes))\s*((`))
^^^ whitespace

\s*+(?:(?:(\bstyled)(?:(\.)\s*(\w+))))\s*((`))
^^^ whitespace
```

the whitespace takes on a new scope too, for example `entity.name.function.js`. Depending on the theme, this can manifest itself in different ways. In mine for example, the selection invisibles get a color:

selection

Also, it messes with symbols because the whitespace becomes part of it:

symbol

**Comment by garetmckinley** [comment]
Oh wow *facepalm*, I developed it with invisibles off, didn't realize they were effected by the syntax definitions. Would you like me to open up a new PR with these changes addressed?

**Comment by zertosh** [comment]
@garetmckinley yeah please. I suggest you move `styled-components` immediately above `support-class` in `expression`, and follow the regex pattern that's used by the things in `support-other`.

**Comment by zertosh** [comment]
Oh and please @ mention me, otherwise I'm really bad at checking notifications :p

**Comment by garetmckinley** [comment]
Will do, thanks. Originally this was a direct port of the [Atom package](https://github.com/gandm/language-babel/search?utf8=%E2%9C%93&q=injectGlobal&type=Code), now I'm curious whether the Atom one has similar issues or if it matches whitespace differently than sublime.

**Comment by zertosh** [comment]
Atom ignores it. https://github.com/gandm/language-babel uses this fact in order to get around the limitation of matching across lines, which results in better syntax highlighting. But, IMHO, it's incorrect because IF you did want to scope whitespace to give it a color (because it's significant for some reason), then you can't.

**Comment by neverfox** [comment]
Is there a way to install from the master branch to get this feature prior to a release?

**Comment by garetmckinley** [comment]
Yeah, just clone the repo to your sublime packages directory.

**Comment by ericbiewener** [comment]
Great job with this! I'm using this PR with my Sublime and noticed the following syntax highlighting issues:

1. `styled(...)` syntax loses all highlighting
2. `transform:` property isn't highlighted correctly

image

**Comment by garetmckinley** [comment]
Thanks for reporting @ericbiewener! I've been pretty busy the past few weeks, but I have a little free time this afternoon, so I'm going to try and fix the issues that have been reported in this thread. Let me know if there's any other rules that don't work!

**Comment by ericbiewener** [comment]
Well, since you're working on it, let me add one more highlighting request ;)

Although the CSS highlighting doesn't work with the `styled(...)` syntax, normal JS string interpolation highlighting does. It would be great to get this within the CSS-highlighted syntax. Compare the `${props => ... }` syntax highlighting below to the version in `Container` in the first screenshot I posted above.

image

**Comment by garetmckinley** [comment]
This is definitely something on my list, but I'm unsure currently how to go about doing that since the CSS is an embedded language file. I'll have to do some research on it, so no promises on that one *yet* :wink:

**Comment by mxstbr** [comment]
Yo dawg, I heard you like syntax highlighting so I added an embedded language in an embedded language file in an embedded language... 😉

```JS
const Box = styled.div`
  background: yellow;
  ${props => props.big && css`
    font-size: 2em;
    color: ${props => props.red ? 'red' : 'blue'}
  `}
`
```

**Comment by mxstbr** [comment]
Wait @zertosh was this shipped?!

**Comment by declanelcocks** [comment]
Also noticed that it doesn't work in this case:

image

And the syntax highlighting for `&:hover` is not working in this case:

image

I assume the above is not working anyway as it normally looks like this:

image

**Comment by garetmckinley** [comment]
If anyone else wants to take a stab at these fixes, please feel free to. My schedule hasn't allowed me to spend very much time on things like this 😕

**Comment by zertosh** [comment]
Checking when I get to my desk :)

- AS

**Comment by mxstbr** [comment]
Thanks @zertosh!

**Comment by zertosh** [comment]
@garetmckinley I made a lot of fixes in 1955e69957c35a751f5c008876cf8694e349931b. Can you give it a quick look before I publish?

**Comment by mxstbr** [comment]
screen shot 2017-03-02 at 12 11 44

I just tried this on a big project, and found this code ^ being syntax highlighted incorrectly. (using the `master` branch of `babel-sublime`) Any ideas why?

**Comment by zertosh** [comment]
@mxstbr can I get the code and the name of theme you're using?

**Comment by mxstbr** [comment]
<details>
  <summary>Code</summary>

```JS
export const Bubble = styled.p`
	display: inline-block;
	flex: 0 0 auto;
	padding: 8px 16px;
	vertical-align: middle;
	border-radius: 16px
	margin-top: 2px;
	font-size: 14px;
	max-width: 60%;
	line-height: 20px;

	&:first-of-type {
		margin-top: 0;
	}

	a {
  		text-decoration: underline;
  		word-wrap: break-word;
  		line-height: inherit;
  		word-break: break-all;
  	}
`;

export const BubbleGroup = styled.div`
	width: 100%;
	margin-top: 8px;

	&:first-of-type {
		margin-top: auto;
	}

	> p {

		background-color: ${props =>
  props.me ? props.theme.brand.default : props.theme.generic.default};
		background-image: ${props =>
  props.me
    ? Gradient(props.theme.brand.alt, props.theme.brand.default)
    : Gradient(props.theme.generic.alt, props.theme.generic.default)}
		color: ${props =>
  props.me ? props.theme.text.reverse : props.theme.text.default};
		float: ${props => props.me ? `right;` : `left;`}
		font-weight: ${props => props.me ? `500` : `400`};
		clear: both;

		&:not(:first-of-type) {
			${props =>
  props.me ? `border-top-right-radius: 4px` : `border-top-left-radius: 4px`};
		}

		&:not(:last-of-type) {
			${props =>
  props.me
    ? `border-bottom-right-radius: 4px`
    : `border-bottom-left-radius: 4px`};
		}

		&::selection {
		  background-color: ${props =>
  props.me ? props.theme.text.default : props.theme.brand.alt};
}
	}
`;
```

</details>

Color scheme: `SublimeLinter/base16-ocean.dark (SL).tmTheme`, theme: `Spacegray.sublime-theme`

**Comment by zertosh** [comment]
@mxstbr it's working as expected.

The s-c section is matched by a CSS grammar that's very close to the one included by Sublime. So if you grab your s-c css code, put it in a new view, and set the grammar to CSS, that should approximate what the s-c code should look like with your theme – and your code looks like your screenshots under `base16-ocean`.

As far as the interpolations in `BubbleGroup`, that brokeness is a limitation of the grammars. The content of `styled.div` is matched as CSS, and CSS doesn't have `${}` interpolations, which is why it looks broken.

**Comment by mxstbr** [comment]
Ah that's fair. Other than that everything works perfectly!

**Comment by danreeves** [comment]
@zertosh does that mean it would be possible to add `${}` interpolations and CSS grammar together as a new `styled-components` grammar so we could have it highlighting properly, or is that a terrible idea?

**Comment by mxstbr** [comment]
Any news on this being published? It's been sitting there for a while now... :cry:

**Comment by zertosh** [comment]
This implementation is not so great. I made lots of fixes in https://github.com/babel/babel-sublime/commit/1955e69957c35a751f5c008876cf8694e349931b, but I'm afraid to release it because it's still not-so-great and I don't really want to "support" it (in the address issues kinda way - not that it shouldn't be in the grammar). From what I understand of how styled-components works, the existing grammar's handling of CSS leaves a lot to be desired. So I don't really know how to proceed :/

**Comment by mxstbr** [comment]
I'm happy to make it its own plugin under the `styled-components` org with what we have right now? What do you think about that, then at least we have something :wink:

**Comment by zertosh** [comment]
@mxstbr not sure what you mean by that... are you saying that instead of `- include: source.js.css` it includes some other grammar?

**Comment by mxstbr** [comment]
No I mean extracting that part and making it it's own plugin, or can Sublime not run two syntax highlighters side-by-side?

**Comment by zertosh** [comment]
@mxstbr that's not how grammars work :/

**Comment by mxstbr** [comment]
That sucks, I guess we just gotta fork it then and publish it as `styled-babel-sublime` or something?

**Pull request merged**
