### PR TITLE
Fix for static class properties

### PR DESCRIPTION
**Pull request by Xazzzi**
Before:
image

After:
image

Should help comrades in #309.

### CODE REVIEW

**Comment by mareksuscak** [comment]
This doesn't work for me in ST 3126. Perhaps need to update `*.tmLanguage` and `*.sublime-syntax` files as well?

**Comment by amsul** [comment]
@mareksuscak can we please get this merged? 😃 

If there's any work left to be done here, I wouldn't mind helping.

**Comment by mareksuscak** [comment]
@amsul I'd love to but I don't have the merging permission.

**Comment by leontastic** [comment]
@Xazzzi Great job with this, I'll be so happy once this is fixed! Been irking me for ages.

@zertosh Do you think you could merge this? Don't know if you've seen this, you just looked like the maintainer based on the commits...

**Comment by jcowley** [comment]
This doesn't seem to work for me on ST 3126, even after building the .tmLanguage file.

@mareksuscak Did you do something other than use [AAAPackageDev](https://github.com/SublimeText/PackageDev) to build the `JavaScript (Babel).tmLanguage` file and then update the files in your `<data_path>/Packages/Babel` directory?

**Comment by mareksuscak** [comment]
@jcowley I couldn't figure out how to build it so I updated `JavaScript (Babel).YAML-tmLanguage` directly. Make sure to update the YAML version. I can't remember if I did anything else or not. I may have deleted the other syntax file but I'm not sure now.

**Comment by Danter7** [comment]
What about no static properties like so?
image

**Comment by joe2son** [comment]
Good guy @Xazzzi saving me from my syntax-highlighting OCD. Thanks bro.

**Pull request closed without merging**
