### PR TITLE
Add Zeus Color Scheme

### PR DESCRIPTION
**Pull request by zaynali53**
@zertosh I've made a color scheme based on babel-sublime. ES6 and JSX ready.

es6-jsx-sublime-view

Here's my repo https://github.com/zaynali53/Zeus-Theme.

### CODE REVIEW

**Comment by zertosh** [comment]
nice! There's a section in the README for them https://github.com/babel/babel-sublime#suggested-resources

Can you submit a PR adding a link to it there? Also, can you make sure the screenshot is exactly 728px wide, so that it doesn't scale in the GitHub view?

**Comment by zaynali53** [comment]
Sure @zertosh

**Comment by zaynali53** [comment]
@zertosh Submitted PR with exact 728px preview Image.

**Comment by zertosh** [comment]
sorry @zaynali53 I don't ship themes[1] with babel-sublime - users can add them on their own. Oceanic Next (from the README) isn't included, I just link to it. I'd be more than happy to add a link to yours too. So please remove the tmTheme, and put yours after Oceanic (he was here before you - no skipping the line).

[1]: Monokai Phoenix is included as a "starter" theme because the stock Monokai is pretty bad. And Next is a debug theme.

**Comment by zaynali53** [comment]
@zertosh Yes got it. I've submitted a new PR containing the link now. Actually it's my starter experience of github contribution so sorry about my mistakes.

**Comment by zertosh** [comment]
@zaynali53 I went to try to download the theme from Package Control to try it out, and it's not there.

**Comment by zaynali53** [comment]
I've submitted the PR to package control but it's not being reviewed yet.

**Comment by zaynali53** [comment]
@zertosh I've submitted the PR to package control but it's not being reviewed yet.

**Comment by zaynali53** [comment]
@zertosh Yes. I've submitted the PR to package control 3 days ago but it's not being reviewed yet. 
Here's the <a href='https://github.com/wbond/package_control_channel/pull/4474'> PR </a>

**Comment by zaynali53** [comment]
@zertosh Zeus Theme is Added in Package Control. You can try it now <a href="https://packagecontrol.io/packages/Zeus">Zeus Theme</a>

**Pull request closed without merging**
