### PR TITLE
Added WeakSet and emmet support for jsx syntax

### PR DESCRIPTION
**Pull request by zaynali53**

### CODE REVIEW

**Comment by zertosh** [comment]
Thanks! Can you squash the commits? And why there a change to scope?

**Comment by zaynali53** [comment]
Emmet's default is to not support JS files and i end up defining a keybinding provided by <a href='https://github.com/allanhortle'>Allan Hortle</a> in his <a href='https://github.com/allanhortle/JSX'>JSX</a> package. I also find the scope defined in the .tmLanguage so i added source.js.jsx there and removed keybinding and it worked like a charm.

**Comment by zertosh** [comment]
Ok cool, fair enough about the scope.  So two things before I can merge this:

1. squash your commits,
2. the `tmLanguage` file is generated from the `YAML-tmLanguage` (see [contributing](https://github.com/babel/babel-sublime#contributing)). so make the scope change in the YAML file.

**Comment by zaynali53** [comment]
Sorry but i don't know how to squash my commits. i'm using github webapp and i didn't find how to do it

**Pull request closed without merging**
