### PR TITLE
Generalized function literal definition

### PR DESCRIPTION
**Pull request by yangsu**
Original Behavior

image

Corrected:

image

The symbol lists also now work properly for multi line function declarations

### CODE REVIEW

**Comment by yangsu** [comment]
PTAL @zertosh

**Comment by zertosh** [comment]
The problem is that then go to definition won't work.

**Comment by yangsu** [comment]
This works when I tested it? This is what I've been using for the past couple of days and it seems to work well.

There's one issue. This will highlight some values as functions as well.

```
editor.Document.defaultDocument_ = null;
```

**Comment by zertosh** [comment]
I'm re-writing the grammar, but this will still be an issue (see #293). Your solution causes issues with Goto Symbol/Definition. Sorry.

**Pull request closed without merging**
