### PR TITLE
[wip] The Great Flow of 2016

### PR DESCRIPTION
**Pull request by zertosh**
ctlxw

### CODE REVIEW

**Comment by cesarandreu** [comment]
Awesome! Very excited for this :D.

**Comment by akovalev** [comment]
```js 
class Sound extends Model
```
@zertosh that's classic :)

**Comment by zertosh** [comment]
@akovalev hehe that's what v2 would look like if it used es6 classes :smile:

**Comment by zertosh** [comment]
Almost there...

ibcvv
mholw

**Comment by zertosh** [comment]
I forgot how ugly stock monokai was

niqyf

**Comment by thejameskyle** [comment]
This is awesome, want to make a blog post when you release it?

**Comment by zertosh** [comment]
@thejameskyle Thanks! For sure! :smile:

**Comment by thejameskyle** [comment]
It would be great to compile all the various sublime tools you can use to have an awesome Sublime setup for ES6/JSX/Flow.

**Comment by zertosh** [comment]
Once I've got the syntax highlighting done, I'm going to build a plugin for flow integration. I'm thinking it can just be a SublimeLinter plugin.

**Comment by frantic** [comment]
@zertosh – let's talk, maybe we could use upcoming hackathon to build a proper plugin. There is already [SublimeLinter-flow](https://github.com/SublimeLinter/SublimeLinter-flow) but it doesn't seem to be actively maintained and certainly doesn't have autocomplete, types info, jump to definition, etc. Also see [this](https://github.com/frantic/sublime/blob/master/flow_type_at_pos.py).

**Comment by aziz** [comment]
@zertosh what's the color scheme you're using for these screenshots?

**Comment by zertosh** [comment]
@aziz: that's my personal theme, which is a fork of [dracula](https://github.com/zenorocha/dracula-theme). I keep it [here](https://github.com/zertosh/dracula-theme/tree/dark) in a branch called "dark".

**Comment by aziz** [comment]
Looks great, thanks.

**Comment by gausie** [comment]
Looking forward to this being merged.

**Comment by zertosh** [comment]
This experiment was a giant bust. See "re-rewrite babel-sublime" #293.

**Pull request closed without merging**
