### PR TITLE
Update list of Node core modules

### PR DESCRIPTION
**Pull request by sindresorhus**
From: https://github.com/sindresorhus/builtin-modules/blob/master/builtin-modules.json

### CODE REVIEW

**Comment by zertosh** [comment]
Thanks! Some are already matched separately because they have methods/props are also matched. Can you remove [`console`](https://github.com/babel/babel-sublime/blob/52b1a26a21e717eacbcd96048e8289b08ac2a0d5/JavaScript%20(Babel).YAML-tmLanguage#L1099) and [`module`](https://github.com/babel/babel-sublime/blob/52b1a26a21e717eacbcd96048e8289b08ac2a0d5/JavaScript%20(Babel).YAML-tmLanguage#L1121)?

**Comment by sindresorhus** [comment]
Fixed.

**Comment by zertosh** [comment]
Thanks!

**Comment by zertosh** [comment]
Published as v6.1.0

**Pull request merged**
